Repository TinU-Official/TinU-Server, pull requests merged in 2024-12, with the labels that each got.

#54 TINU-88 ⭐ [Feature] : Prometheus 세팅
  .github/workflows/action.yml
  build.gradle
Labels: ⭐ Feature

#58 JwtTtil class 작성
  build.gradle
  src/main/kotlin/com/tinuproject/tinu/security/jwt/JwtUtil.kt
Labels: ⭐ Feature

#60 [issue59] JwtTokenFilter class Feat
  src/main/kotlin/com/tinuproject/tinu/security/filter/JwtTokenFilter.kt
Labels: ⭐ Feature

#62 [issue61] [Feat] : Exception Class Add
  src/main/kotlin/com/tinuproject/tinu/domain/exception/base/BaseCode.kt
  src/main/kotlin/com/tinuproject/tinu/domain/exception/base/BaseErrorCode.kt
  src/main/kotlin/com/tinuproject/tinu/domain/exception/base/BaseException.kt
  src/main/kotlin/com/tinuproject/tinu/domain/exception/base/ErrorResponseDTO.kt
  src/main/kotlin/com/tinuproject/tinu/domain/exception/base/ResponseDTO.kt
  src/main/kotlin/com/tinuproject/tinu/domain/exception/token/ExpiredTokenException.kt
  src/main/kotlin/com/tinuproject/tinu/domain/exception/token/InvalidedToken.kt
  src/main/kotlin/com/tinuproject/tinu/domain/exception/token/NotFoundTokenException.kt
  src/main/kotlin/com/tinuproject/tinu/domain/exception/token/TokenErrorCode.kt
Labels: ⭐ Feature

#57 TINU-64 ⭐ [Feature] : Presigned URL 테스트
  .github/workflows/action.yml
  build.gradle
  docker-compose.yml
  src/main/kotlin/com/tinuproject/tinu/DTO/ResponseDTO.kt
  src/main/kotlin/com/tinuproject/tinu/s3/config/S3Config.kt
  src/main/kotlin/com/tinuproject/tinu/s3/controller/S3Controller.kt
  src/main/kotlin/com/tinuproject/tinu/s3/dto/request/S3DeleteRequest.kt
  src/main/kotlin/com/tinuproject/tinu/s3/dto/request/S3UploadAbortRequest.kt
  src/main/kotlin/com/tinuproject/tinu/s3/dto/request/S3UploadCompleteRequest.kt
  src/main/kotlin/com/tinuproject/tinu/s3/dto/request/S3UploadInitiateRequest.kt
  src/main/kotlin/com/tinuproject/tinu/s3/dto/request/S3UploadPresignedUrlRequest.kt
  src/main/kotlin/com/tinuproject/tinu/s3/dto/response/S3UploadCompleteResponse.kt
  src/main/kotlin/com/tinuproject/tinu/s3/dto/response/S3UploadCreatePresignedUrlResponse.kt
  src/main/kotlin/com/tinuproject/tinu/s3/dto/response/S3UploadInitiateResponse.kt
  src/main/kotlin/com/tinuproject/tinu/s3/service/S3Service.kt
  src/main/kotlin/com/tinuproject/tinu/s3/service/S3ServiceImpl.kt
Labels: ⭐ Feature

#65 Issue63/refresh token logic feat
  build.gradle
  src/main/kotlin/com/tinuproject/tinu/domain/entity/RefreshToken.kt
  src/main/kotlin/com/tinuproject/tinu/domain/enum/Social.kt
  src/main/kotlin/com/tinuproject/tinu/domain/exception/token/InvalidedToken.kt
  src/main/kotlin/com/tinuproject/tinu/domain/socialmember/repository/SocialMemberRepository.kt
  src/main/kotlin/com/tinuproject/tinu/domain/socialmember/service/SocialMemberService.kt
  src/main/kotlin/com/tinuproject/tinu/security/RefreshTokenRepository.kt
  src/main/kotlin/com/tinuproject/tinu/security/config/SecurityConfig.kt
  src/main/kotlin/com/tinuproject/tinu/security/filter/JwtTokenFilter.kt
  src/main/kotlin/com/tinuproject/tinu/security/oauth2/dto/KakaoUserInfo.kt
  src/main/kotlin/com/tinuproject/tinu/security/oauth2/dto/NaverUserInfo.kt
  src/main/kotlin/com/tinuproject/tinu/security/oauth2/dto/OAuth2UserInfoDto.kt
  src/main/kotlin/com/tinuproject/tinu/security/oauth2/dto/UserInfoDto.kt
  src/main/kotlin/com/tinuproject/tinu/security/oauth2/handler/OAuthLoginFailureHandler.kt
  src/main/kotlin/com/tinuproject/tinu/security/oauth2/handler/OAuthLoginSuccessHandler.kt
Labels: ⭐ Feature

#66 [issue63] [Feat] RefreshToken logic 완성
  src/main/kotlin/com/tinuproject/tinu/domain/exception/token/InvalidedTokenException.kt
  src/main/kotlin/com/tinuproject/tinu/domain/token/Tokens.kt
  src/main/kotlin/com/tinuproject/tinu/domain/token/refreshtoken/RefreshTokenController.kt
  src/main/kotlin/com/tinuproject/tinu/domain/token/refreshtoken/repository/RefreshTokenRepository.kt
  src/main/kotlin/com/tinuproject/tinu/domain/token/refreshtoken/service/RefreshTokenService.kt
  src/main/kotlin/com/tinuproject/tinu/domain/token/refreshtoken/service/RefreshTokenServiceImpl.kt
  src/main/kotlin/com/tinuproject/tinu/security/config/SecurityConfig.kt
  src/main/kotlin/com/tinuproject/tinu/security/jwt/JwtUtil.kt
  src/main/kotlin/com/tinuproject/tinu/security/oauth2/handler/OAuthLoginSuccessHandler.kt
  src/main/kotlin/com/tinuproject/tinu/web/CookieGenerator.kt
Labels: ⭐ Feature

#68 [issue67] [Feat] : global exception handler add, tokenException handl…
  src/main/kotlin/com/tinuproject/tinu/GlobalExceptionHandler.kt
  src/main/kotlin/com/tinuproject/tinu/domain/exception/base/BaseException.kt
  src/main/kotlin/com/tinuproject/tinu/domain/token/refreshtoken/controller/RefreshTokenController.kt
  src/main/kotlin/com/tinuproject/tinu/security/config/SecurityConfig.kt
  src/main/kotlin/com/tinuproject/tinu/security/filter/JwtTokenFilter.kt
  src/main/kotlin/com/tinuproject/tinu/web/ResponseEntityGenerator.kt
  src/main/resources/static/loginpage.html
Labels: ⭐ Feature

#70 [issue69] [Refactor] Modify entire logic
  src/main/kotlin/com/tinuproject/tinu/domain/exception/base/BaseException.kt
  src/main/kotlin/com/tinuproject/tinu/domain/exception/base/ErrorResponseDTO.kt
  src/main/kotlin/com/tinuproject/tinu/domain/exception/base/ResponseDTO.kt
  src/main/kotlin/com/tinuproject/tinu/domain/token/refreshtoken/controller/RefreshTokenController.kt
  src/main/kotlin/com/tinuproject/tinu/domain/token/refreshtoken/service/RefreshTokenService.kt
  src/main/kotlin/com/tinuproject/tinu/domain/token/refreshtoken/service/RefreshTokenServiceImpl.kt
  src/main/kotlin/com/tinuproject/tinu/security/config/SecurityConfig.kt
  src/main/kotlin/com/tinuproject/tinu/security/filter/ExceptionHandlerFilter.kt
  src/main/kotlin/com/tinuproject/tinu/security/filter/JwtTokenFilter.kt
  src/main/kotlin/com/tinuproject/tinu/security/jwt/JwtUtil.kt
  src/main/kotlin/com/tinuproject/tinu/web/ResponseEntityGenerator.kt
Labels: ♻️ Refactor

#72 [issue71] [Refactor] : clear TODO
  src/main/kotlin/com/tinuproject/tinu/GlobalExceptionHandler.kt
  src/main/kotlin/com/tinuproject/tinu/security/config/SecurityConfig.kt
  src/main/kotlin/com/tinuproject/tinu/security/filter/JwtTokenFilter.kt
  src/main/kotlin/com/tinuproject/tinu/security/jwt/JwtUtil.kt
Labels: ♻️ Refactor

#74 [issue73] [Refactor] Custom Filter's super class changer
  src/main/kotlin/com/tinuproject/tinu/domain/token/refreshtoken/controller/RefreshTokenController.kt
  src/main/kotlin/com/tinuproject/tinu/security/config/SecurityConfig.kt
  src/main/kotlin/com/tinuproject/tinu/security/filter/ExceptionHandlerFilter.kt
  src/main/kotlin/com/tinuproject/tinu/security/filter/JwtTokenFilter.kt
Labels: ♻️ Refactor

#77 [issue76] [Refactor] action.yml add social login enviroment variable
  .github/workflows/action.yml
Labels: ♻️ Refactor

#83 [issue82] [FIX] property_sorurce annotation delete
  src/main/kotlin/com/tinuproject/tinu/security/jwt/JwtUtil.kt
  src/main/kotlin/com/tinuproject/tinu/security/oauth2/handler/OAuthLoginSuccessHandler.kt
Labels: 🔨 Fix

#85 [issue84] [FIX] BaseException's abstract
  src/main/kotlin/com/tinuproject/tinu/domain/exception/base/BaseException.kt
  src/main/kotlin/com/tinuproject/tinu/domain/exception/base/ErrorCode.kt
Labels: 🔨 Fix

#86 [issue84] [Fix] BaseException implement fix
  src/main/kotlin/com/tinuproject/tinu/domain/exception/token/ExpiredTokenException.kt
  src/main/kotlin/com/tinuproject/tinu/domain/exception/token/InvalidedTokenException.kt
  src/main/kotlin/com/tinuproject/tinu/domain/exception/token/NotFoundTokenException.kt
Labels: 🔨 Fix
