Repository TinU-Official/TinU-Server, pull requests merged in 2025-03, with the labels that each got.

#118 [FIX] CI/CD action trigger를 PR open에서 push로 수정합니다.
  .github/workflows/action.yml
Labels: 🔨 Fix

#121 [FEAT] Custom Filter 관련 단순 로직 (CRUD 완료)
  src/main/kotlin/com/tinuproject/tinu/domain/category/repository/CategoryRepository.kt
  src/main/kotlin/com/tinuproject/tinu/domain/customcategory/repository/CustomCategoryRepository.kt
  src/main/kotlin/com/tinuproject/tinu/domain/customfilter/controller/CustomFilterController.kt
  src/main/kotlin/com/tinuproject/tinu/domain/customfilter/dto/client_controller/request/CreateCustomFilter.kt
  src/main/kotlin/com/tinuproject/tinu/domain/customfilter/dto/client_controller/request/DeleteCustomFilter.kt
  src/main/kotlin/com/tinuproject/tinu/domain/customfilter/dto/client_controller/request/UpdateCustomFilter.kt
  src/main/kotlin/com/tinuproject/tinu/domain/customfilter/dto/client_controller/response/SelectCustomFilter.kt
  src/main/kotlin/com/tinuproject/tinu/domain/customfilter/repository/CustomFilterRepository.kt
  src/main/kotlin/com/tinuproject/tinu/domain/customfilter/service/CustomFilterService.kt
  src/main/kotlin/com/tinuproject/tinu/domain/customfilter/service/CustomFilterServiceImpl.kt
  src/main/kotlin/com/tinuproject/tinu/domain/entity/CustomFilter.kt
  src/main/kotlin/com/tinuproject/tinu/domain/exception/base/ErrorCode.kt
  src/main/kotlin/com/tinuproject/tinu/domain/exception/customfilter/NotExistCustomFilter.kt
Labels: ⭐ Feature

#123 [FEAT] 프로젝트 Swagger 적용 및 에러 ApiResponse 자동화 구현
  build.gradle
  src/main/kotlin/com/tinuproject/tinu/DTO/ErrorResponse.kt
  src/main/kotlin/com/tinuproject/tinu/DTO/ResponseDTO.kt
  src/main/kotlin/com/tinuproject/tinu/GlobalExceptionHandler.kt
  src/main/kotlin/com/tinuproject/tinu/domain/exception/base/BaseCode.kt
  src/main/kotlin/com/tinuproject/tinu/domain/exception/base/BaseErrorCode.kt
  src/main/kotlin/com/tinuproject/tinu/domain/exception/base/BaseException.kt
  src/main/kotlin/com/tinuproject/tinu/domain/exception/base/ErrorCode.kt
  src/main/kotlin/com/tinuproject/tinu/domain/member/controller/MemberController.kt
  src/main/kotlin/com/tinuproject/tinu/domain/member/controller/RegisterController.kt
  src/main/kotlin/com/tinuproject/tinu/domain/member/dto/client_controller/response/TestDTO.kt
  src/main/kotlin/com/tinuproject/tinu/domain/token/refreshtoken/controller/RefreshTokenController.kt
  src/main/kotlin/com/tinuproject/tinu/domain/university/controller/UniversityController.kt
  src/main/kotlin/com/tinuproject/tinu/security/config/SecurityConfig.kt
  src/main/kotlin/com/tinuproject/tinu/security/filter/ExceptionHandlerFilter.kt
  src/main/kotlin/com/tinuproject/tinu/swagger/adaptor/SwaggerExceptionResponseAdaptor.kt
  src/main/kotlin/com/tinuproject/tinu/swagger/annotation/ExampleHolder.kt
  src/main/kotlin/com/tinuproject/tinu/swagger/annotation/SwaggerExceptionResponses.kt
  src/main/kotlin/com/tinuproject/tinu/swagger/config/SwaggerConfig.kt
  src/main/kotlin/com/tinuproject/tinu/web/NullResponse.kt
  src/main/kotlin/com/tinuproject/tinu/web/ResponseEntityGenerator.kt
Labels: ⭐ Feature

#128 Tinu 146/server environment setting
  docker-compose.yml
  nginx/conf.d/app.conf
Labels: ⭐ Feature

#129 [FIX] nginx docker image name edit
  docker-compose.yml
Labels: 🔨 Fix

#130 [DELETE] docker-compose, nginx file delete(reason : environment setup…
  docker-compose.yml
  nginx/conf.d/app.conf
Labels: 🔥 Delete, ⭐ Feature
